import { parseDxf, parseGeoJson } from './src/dxf.js';
import { boundsOf, mergeBounds } from './src/geometry.js';
import { drawReport } from './src/render.js';
import { downloadReportPdf } from './src/pdf.js';

const state = { config: null, baseImage: null, string: null, areas: [], boundsMode: 'auto', manualBounds: null };
const $ = (id) => document.getElementById(id);

function notify(message, type = '') { const toast = $('toast'); toast.textContent = message; toast.className = `toast show ${type}`; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.className = 'toast'; }, 4200); }
function readNumber(id) { const value = Number($(id).value); return Number.isFinite(value) && value >= 0 ? value : 0; }
function dateLabel() { const value = $('date').value; return value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : 'data não informada'; }
function model() { return { meta: { company: $('company').value.trim(), date: $('date').value, time: $('time').value, location: $('location').value.trim(), observation: $('observation').value.trim(), dateLabel: dateLabel() }, baseImage: state.baseImage, string: state.string, areas: state.areas, radii: { people: readNumber('peopleRadius'), machine: readNumber('machineRadius') }, boundsMode: state.boundsMode, manualBounds: state.manualBounds }; }
function allEntities() { return [state.string?.entities || [], ...state.areas.map((area) => area.entities || [])].flat(); }
function updateMetrics(renderResult) { $('geometryCount').textContent = allEntities().length; $('endpointCount').textContent = renderResult.endpointCount; $('scaleWarning').textContent = state.boundsMode === 'auto' ? 'extensão automática' : 'limites informados'; $('statusText').textContent = state.string || state.areas.length ? 'Dados prontos para conferência' : 'Aguardando dados'; $('previewCaption').textContent = state.string || state.areas.length ? `Prancha atualizada em ${new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}.` : 'A prévia será atualizada conforme os dados forem preenchidos.'; }
function render() { if (!state.config) return; const result = drawReport($('reportCanvas'), model(), state.config); updateMetrics(result); }

function setImage(file) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error('Não foi possível ler a imagem selecionada.')); image.src = URL.createObjectURL(file); }); }
async function handleBackground(file) { state.baseImage = await setImage(file); $('backgroundState').textContent = `${file.name} carregado para a prévia.`; render(); }
async function handleString(file) { if (file.size > state.config.validation.maxDxfBytes) throw new Error('O DXF excede o limite de 50 MB.'); const parsed = parseDxf(await file.text()); state.string = { name: file.name, ...parsed }; $('stringState').textContent = `${file.name} · ${parsed.entities.length} entidades${parsed.unsupported.length ? ` · ${parsed.unsupported.length} tipos ignorados` : ''}`; render(); }
async function parseAreaFile(file) { if (file.size > state.config.validation.maxDxfBytes) throw new Error(`O arquivo ${file.name} excede o limite de 50 MB.`); const extension = file.name.toLowerCase().split('.').pop(); const parsed = extension === 'dxf' ? parseDxf(await file.text()) : parseGeoJson(await file.text()); return { id: `${file.name}-${file.lastModified}-${Math.random()}`, name: file.name, label: file.name.replace(/\.[^.]+$/, ''), status: /liberad/i.test(file.name) ? 'liberado' : 'evacuar', ...parsed }; }
function renderAreaList() { const container = $('areaList'); container.innerHTML = ''; if (!state.areas.length) { container.innerHTML = '<div class="empty-state">Nenhuma área carregada.</div>'; return; } state.areas.forEach((area) => { const row = document.createElement('div'); row.className = 'area-item'; row.innerHTML = `<input aria-label="Nome da área ${area.name}" value="${area.label.replace(/&/g, '&amp;').replace(/"/g, '&quot;')}" maxlength="70"><select aria-label="Classificação da área ${area.name}"><option value="evacuar">Evacuar</option><option value="liberado">Liberado</option></select>`; const input = row.querySelector('input'); const select = row.querySelector('select'); input.addEventListener('input', () => { area.label = input.value; render(); }); select.value = area.status; select.addEventListener('change', () => { area.status = select.value; render(); }); container.append(row); }); }
function parseManualBounds() { const values = ['minX', 'minY', 'maxX', 'maxY'].map((id) => Number($(id).value)); if (values.some((value) => !Number.isFinite(value))) return null; const [minX, minY, maxX, maxY] = values; if (maxX <= minX || maxY <= minY) throw new Error('Os limites do mapa precisam formar uma extensão válida.'); return { minX, minY, maxX, maxY }; }
async function loadReference() { const image = await setImage(await fetch('assets/referencia-base.jpg').then((response) => { if (!response.ok) throw new Error('A imagem de referência não está disponível.'); return response.blob(); })); state.baseImage = image; $('backgroundState').textContent = 'Mapa de referência carregado, sem o painel lateral do exemplo.'; render(); notify('Mapa de referência carregado.'); }
function clearAll() { state.baseImage = null; state.string = null; state.areas = []; state.boundsMode = 'auto'; state.manualBounds = null; $('reportForm').reset(); $('autoExtent').checked = true; $('manualBounds').hidden = true; $('backgroundState').textContent = 'Sem imagem de fundo. A prancha usará o fundo técnico.'; $('stringState').textContent = 'Nenhuma poligonal carregada.'; renderAreaList(); render(); notify('Formulário limpo.'); }
function wire() {
  $('backgroundFile').addEventListener('change', async (event) => { if (!event.target.files[0]) return; try { await handleBackground(event.target.files[0]); } catch (error) { notify(error.message, 'error'); } });
  $('stringFile').addEventListener('change', async (event) => { if (!event.target.files[0]) return; try { await handleString(event.target.files[0]); } catch (error) { state.string = null; $('stringState').textContent = error.message; notify(error.message, 'error'); render(); } });
  $('areaFiles').addEventListener('change', async (event) => { const files = [...event.target.files]; if (files.length + state.areas.length > state.config.validation.maxAreaFiles) { notify(`Limite de ${state.config.validation.maxAreaFiles} arquivos de área.`, 'error'); return; } for (const file of files) { try { state.areas.push(await parseAreaFile(file)); } catch (error) { notify(`${file.name}: ${error.message}`, 'error'); } } renderAreaList(); render(); event.target.value = ''; });
  ['company', 'date', 'time', 'location', 'observation', 'peopleRadius', 'machineRadius'].forEach((id) => $(id).addEventListener('input', render));
  $('autoExtent').addEventListener('change', () => { state.boundsMode = $('autoExtent').checked ? 'auto' : 'manual'; $('manualBounds').hidden = $('autoExtent').checked; if (!$('autoExtent').checked) { const bounds = mergeBounds([boundsOf(state.string?.entities || []), ...state.areas.map((area) => boundsOf(area.entities || []))]); if (bounds) { Object.entries(bounds).forEach(([key, value]) => { const id = { minX: 'minX', minY: 'minY', maxX: 'maxX', maxY: 'maxY' }[key]; $(id).value = value; }); } } render(); });
  ['minX', 'minY', 'maxX', 'maxY'].forEach((id) => $(id).addEventListener('input', () => { try { state.manualBounds = parseManualBounds(); render(); } catch { } }));
  $('referenceButton').addEventListener('click', async () => { try { await loadReference(); } catch (error) { notify(error.message, 'error'); } });
  $('clearButton').addEventListener('click', clearAll);
  $('pdfButton').addEventListener('click', () => { try { if (!state.string && !state.areas.length) throw new Error('Adicione ao menos uma poligonal ou área antes de gerar o PDF.'); if (state.boundsMode === 'manual') state.manualBounds = parseManualBounds(); downloadReportPdf($('reportCanvas'), model(), state.config); notify('PDF gerado e baixado.'); } catch (error) { notify(error.message, 'error'); } });
}

async function start() { try { const response = await fetch('./config.json', { cache: 'no-store' }); if (!response.ok) throw new Error('Não foi possível carregar a configuração do projeto.'); state.config = await response.json(); $('appName').textContent = state.config.app.name; $('appEyebrow').textContent = state.config.app.eyebrow; $('appVersion').textContent = `v${state.config.app.version}`; wire(); render(); } catch (error) { $('statusText').textContent = 'Erro de configuração'; notify(error.message, 'error'); } }
start();
