import { parseDxf, parseGeoJson } from './src/dxf.js';
import { boundsOfContours, buildRadiusContours, boundsOf, flattenStringEntities, mergeBounds } from './src/geometry.js';
import { decodeGeoTiff } from './src/geotiff.js';
import { drawReport } from './src/render.js';
import { downloadReportPdf } from './src/pdf.js';
import { getOrthoOverride, listOrthoOverrides, removeOrthoOverride, saveOrthoOverride } from './src/ortho-store.js';

const state = { config: null, baseImage: null, baseImages: [], orthoLayers: [], logoImage: null, enaexLogo: null, blockingIcon: null, cardIcon: null, strings: [], areas: [], firingPoints: [], blockingPoints: [], cardPoints: [], placementMode: null, lastRender: null, radiusContours: [], contourKey: '', boundsMode: 'auto', manualBounds: null, orthoOverrides: new Map(), savedOverrideIds: new Set() };
const $ = (id) => document.getElementById(id);

function notify(message, type = '') { const toast = $('toast'); toast.textContent = message; toast.className = `toast show ${type}`; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.className = 'toast'; }, 4200); }
function readNumber(id) { const value = Number($(id).value); return Number.isFinite(value) && value >= 0 ? value : 0; }
function radii() { return { people: readNumber('peopleRadius'), machine: readNumber('machineRadius') }; }
function dateLabel() { const value = $('date').value; return value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : 'data não informada'; }
function stringEntities() { return flattenStringEntities(state.strings); }
function model() { return { meta: { company: $('company').value.trim(), date: $('date').value, time: $('time').value, location: $('location').value.trim(), observation: $('observation').value.trim(), dateLabel: dateLabel() }, baseImage: state.baseImage, baseImages: state.baseImages, logoImage: state.logoImage, blockingIcon: state.blockingIcon, cardIcon: state.cardIcon, firingIcon: null, strings: state.strings, areas: state.areas, firingPoints: state.firingPoints, blockingPoints: state.blockingPoints, cardPoints: state.cardPoints, radii: radii(), radiusContours: state.radiusContours, boundsMode: state.boundsMode, manualBounds: state.manualBounds }; }
function allEntities() { return [stringEntities(), ...state.areas.map((area) => area.entities || [])].flat(); }
function ensureContours(currentRadii = radii()) { const key = `${state.strings.map((item) => item.id).join('|')}|${currentRadii.people}|${currentRadii.machine}`; if (key !== state.contourKey) { state.radiusContours = buildRadiusContours(stringEntities(), [currentRadii.people, currentRadii.machine]); state.contourKey = key; } }
function updateStatusBadges() { state.areas.forEach((area) => { const badge = document.querySelector(`[data-area-status="${CSS.escape(area.id)}"]`); if (badge) { badge.textContent = area.status === 'evacuar' ? 'RAIO · EVACUAR' : 'FORA DO RAIO · LIBERADO'; badge.className = `area-status ${area.status}`; } }); }
function updateMetrics(renderResult) { $('geometryCount').textContent = allEntities().length; $('endpointCount').textContent = renderResult.endpointCount; $('scaleWarning').textContent = renderResult.extentSource === 'manual' ? 'limites informados' : renderResult.extentSource === 'geometria-e-raios' ? 'geometria + raios' : renderResult.extentSource === 'georreferenciado' ? 'GeoTIFF georreferenciada + raios' : 'extensão automática'; $('extentState').textContent = renderResult.extentSource === 'manual' ? 'Extensão manual ativa. Revise os quatro limites antes de emitir.' : renderResult.extentSource === 'georreferenciado' ? 'Extensão automática inclui a geometria dos raios sobre o ortomosaico georreferenciado.' : renderResult.extentSource === 'geometria-e-raios' ? 'Extensão automática inclui strings, áreas e os raios carregados.' : 'Extensão automática calculada a partir dos dados carregados.'; $('statusText').textContent = state.strings.length || state.areas.length ? 'Dados prontos para conferência' : 'Aguardando dados'; $('previewCaption').textContent = state.strings.length || state.areas.length ? `Prancha atualizada em ${new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}.` : 'A prévia será atualizada conforme os dados forem preenchidos.'; updateStatusBadges(); }
function render() { if (!state.config) return; ensureContours(); state.lastRender = drawReport($('reportCanvas'), model(), state.config); updateMetrics(state.lastRender); }

function loadImageBlob(blob) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { URL.revokeObjectURL(image.src); resolve(image); }; image.onerror = () => reject(new Error('Não foi possível ler a imagem selecionada.')); image.src = URL.createObjectURL(blob); }); }
async function handleBackground(file) { const extension = file.name.toLowerCase().split('.').pop(); const image = ['tif', 'tiff'].includes(extension) ? await decodeGeoTiff(file) : { image: await loadImageBlob(file), bounds: null, name: file.name }; state.baseImages = [...(state.baseImages || []), image]; state.orthoLayers = [...(state.orthoLayers || []), image]; state.baseImage = image; $('backgroundState').textContent = `${state.baseImages.length} imagem(ns) em camadas${image.bounds ? ' · GeoTIFF georreferenciada.' : '.'}`; render(); }
function populateOrthoCatalog() { const select = $('orthomosaicSelect'); select.innerHTML = ''; (state.config.ortomosaicos || []).forEach((item) => { const option = document.createElement('option'); option.value = item.id; option.textContent = `${item.label}${state.savedOverrideIds.has(item.id) ? ' · atualização local' : ''}`; select.append(option); }); }
function selectedOrtho() { return (state.config.ortomosaicos || []).find((item) => item.id === $('orthomosaicSelect').value); }
async function loadCatalogOrthomosaic(item = selectedOrtho()) { if (!item) throw new Error('Nenhum ortomosaico foi configurado no catálogo.'); let image = state.orthoOverrides.get(item.id); let local = Boolean(image); if (!image && state.savedOverrideIds.has(item.id)) { const saved = await getOrthoOverride(item.id); if (saved?.blob) { image = await decodeGeoTiff(saved.blob); image.name = saved.fileName || image.name; state.orthoOverrides.set(item.id, image); local = true; } } const layer = image || await decodeGeoTiff(item.path); state.baseImages = [...(state.baseImages || []), layer]; state.orthoLayers = [...(state.orthoLayers || []), layer]; state.baseImage = layer; $('backgroundState').textContent = `${state.baseImages.length} imagem(ns) em camadas · último: ${item.label}${local ? ' · substituição local ativa.' : ''}`; $('googleState').textContent = 'Chave não configurada'; $('googleState').className = 'status-pill muted'; render(); notify(`Ortomosaico adicionado: ${item.label}.`); }
async function loadProjectGeoTiff() { await loadCatalogOrthomosaic((state.config.ortomosaicos || [])[0]); }
async function loadAllCatalogOrthomosaics() { const entries = state.config.ortomosaicos || []; if (!entries.length) throw new Error('Nenhum ortomosaico foi configurado no catálogo.'); const images = []; for (const item of entries) { try { let image = state.orthoOverrides.get(item.id); if (!image && state.savedOverrideIds.has(item.id)) { const saved = await getOrthoOverride(item.id); if (saved?.blob) { image = await decodeGeoTiff(saved.blob); image.name = saved.fileName || image.name; state.orthoOverrides.set(item.id, image); } } images.push(image || await decodeGeoTiff(item.path)); } catch (error) { notify(`${item.label}: ${error.message}`, 'error'); } } if (!images.length) throw new Error('Nenhum ortomosaico pôde ser carregado.'); state.orthoLayers = images; state.baseImages = images; state.baseImage = images[0]; $('backgroundState').textContent = `${images.length} ortomosaico(s) exibido(s) como camadas georreferenciadas.`; render(); notify(`${images.length} ortofoto(s) carregada(s) no mapa.`); }
async function replaceCatalogOrthomosaic(file) { const item = selectedOrtho(); if (!item) throw new Error('Selecione primeiro qual ortomosaico será substituído.'); if (file.size > state.config.validation.maxDxfBytes * 4) throw new Error('O ortomosaico excede o limite de 200 MB.'); const decoded = await decodeGeoTiff(file); await saveOrthoOverride(item.id, file, { fileName: file.name }); state.savedOverrideIds.add(item.id); state.orthoOverrides.set(item.id, { ...decoded, name: file.name }); populateOrthoCatalog(); $('orthomosaicSelect').value = item.id; state.baseImage = state.orthoOverrides.get(item.id); state.orthoLayers = [state.baseImage]; state.baseImages = [state.baseImage]; $('backgroundState').textContent = `${file.name} · substituição local de ${item.label}.`; render(); notify(`Ortomosaico substituído e salvo nesta máquina: ${item.label}.`); }
async function restoreCatalogOrthomosaic() { const item = selectedOrtho(); if (!item) throw new Error('Selecione primeiro qual ortomosaico será restaurado.'); await removeOrthoOverride(item.id); state.savedOverrideIds.delete(item.id); state.orthoOverrides.delete(item.id); populateOrthoCatalog(); $('orthomosaicSelect').value = item.id; await loadCatalogOrthomosaic(item); notify(`Original restaurado: ${item.label}.`); }
function configureSad69() { if (!globalThis.proj4) throw new Error('O conversor de coordenadas não carregou.'); if (!globalThis.proj4.defs('EPSG:29194')) globalThis.proj4.defs('EPSG:29194', '+proj=utm +zone=24 +south +ellps=aust_SA +towgs84=-57.5,1.0,-41.5 +units=m +no_defs'); }
function geoCenter(bounds) { configureSad69(); const corners = [[bounds.minX, bounds.minY], [bounds.maxX, bounds.maxY]].map((point) => globalThis.proj4('EPSG:29194', 'EPSG:4326', point)); return { lat: (corners[0][1] + corners[1][1]) / 2, lng: (corners[0][0] + corners[1][0]) / 2 }; }
function tileXY(lon, lat, zoom) { const scale = 2 ** zoom; const x = (lon + 180) / 360 * scale; const y = (1 - Math.asinh(Math.tan(lat * Math.PI / 180)) / Math.PI) / 2 * scale; return { x, y }; }
async function loadGoogleSatelliteTiles(bounds) { configureSad69(); const corners = [[bounds.minX, bounds.minY], [bounds.maxX, bounds.maxY]].map((point) => globalThis.proj4('EPSG:29194', 'EPSG:4326', point)); const west = Math.min(corners[0][0], corners[1][0]); const east = Math.max(corners[0][0], corners[1][0]); const south = Math.min(corners[0][1], corners[1][1]); const north = Math.max(corners[0][1], corners[1][1]); let zoom = 16; let topLeft; let bottomRight; let columns; let rows; do { topLeft = tileXY(west, north, zoom); bottomRight = tileXY(east, south, zoom); columns = Math.floor(bottomRight.x) - Math.floor(topLeft.x) + 1; rows = Math.floor(bottomRight.y) - Math.floor(topLeft.y) + 1; if (columns * rows > 36) zoom -= 1; } while (columns * rows > 36 && zoom > 10); const minTileX = Math.floor(topLeft.x); const minTileY = Math.floor(topLeft.y); const canvas = document.createElement('canvas'); canvas.width = columns * 256; canvas.height = rows * 256; const ctx = canvas.getContext('2d'); const jobs = []; for (let y = 0; y < rows; y += 1) for (let x = 0; x < columns; x += 1) jobs.push((async () => { const url = `https://mt1.google.com/vt/lyrs=s&x=${minTileX + x}&y=${minTileY + y}&z=${zoom}`; const response = await fetch(url); if (!response.ok) throw new Error('tile não disponível'); const image = await loadImageBlob(await response.blob()); ctx.drawImage(image, x * 256, y * 256); })()); await Promise.all(jobs); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png')); return loadImageBlob(blob); }
async function loadGoogleSatellite() { const key = $('googleMapsKey').value.trim(); const bounds = mergeBounds((state.baseImages || []).map((entry) => entry?.bounds).concat(state.baseImage?.bounds)); if (!bounds) throw new Error('Carregue primeiro um GeoTIFF georreferenciado para definir a extensão do satélite.'); let image; if (key) { const center = geoCenter(bounds); const span = Math.max(bounds.maxX - bounds.minX, bounds.maxY - bounds.minY); const zoom = Math.max(11, Math.min(18, Math.round(Math.log2(400000 / span)))); const url = `https://maps.googleapis.com/maps/api/staticmap?center=${center.lat},${center.lng}&zoom=${zoom}&size=640x640&scale=2&maptype=satellite&key=${encodeURIComponent(key)}`; const response = await fetch(url); if (!response.ok) throw new Error('A Google Maps Static API não autorizou a imagem. Verifique chave, API habilitada e faturamento.'); image = await loadImageBlob(await response.blob()); } else image = await loadGoogleSatelliteTiles(bounds); state.baseImage = { image, bounds, name: 'Google Satellite' }; state.baseImages = [state.baseImage, ...(state.orthoLayers || []).filter((entry) => entry !== state.baseImage)]; $('googleState').textContent = key ? 'Google ativo' : 'Google Earth ativo sem chave'; $('googleState').className = 'status-pill online'; $('backgroundState').textContent = `Fundo satelital Google aplicado atrás de ${state.orthoLayers?.length || 0} ortofoto(s).`; render(); notify('Fundo satelital Google aplicado sem solicitar chave.'); }
async function applyDefaultPreset() {
  const preset = state.config.defaultPreset || {};
  if (preset.peopleRadius != null) $('peopleRadius').value = preset.peopleRadius;
  if (preset.machineRadius != null) $('machineRadius').value = preset.machineRadius;
  if (preset.loadAllOrthomosaics) await loadAllCatalogOrthomosaics();
  if (preset.loadProjectStrings) await loadBundledStrings();
  if (preset.loadProjectAreas) await loadBundledAreas();
  if (preset.loadSatelliteBackground && state.baseImage?.bounds) await loadGoogleSatellite();
}
async function handleStrings(files) { for (const file of files) { try { if (file.size > state.config.validation.maxDxfBytes) throw new Error('O DXF excede o limite de 50 MB.'); const parsed = parseDxf(await file.text()); state.strings.push({ id: `${file.name}-${file.lastModified}-${Math.random()}`, name: file.name, label: file.name.replace(/\.[^.]+$/, ''), ...parsed }); } catch (error) { notify(`${file.name}: ${error.message}`, 'error'); } } renderStringList(); state.contourKey = ''; render(); }
async function parseAreaFile(file) { if (file.size > state.config.validation.maxDxfBytes) throw new Error(`O arquivo ${file.name} excede o limite de 50 MB.`); const extension = file.name.toLowerCase().split('.').pop(); const parsed = extension === 'dxf' ? parseDxf(await file.text()) : parseGeoJson(await file.text()); return { id: `${file.name}-${file.lastModified}-${Math.random()}`, name: file.name, label: file.name.replace(/\.[^.]+$/, ''), status: 'liberado', ...parsed }; }
async function loadBundledStrings() { const entries = state.config.poligonaisProjeto || []; if (!entries.length) throw new Error('Nenhuma poligonal de projeto foi configurada.'); let loaded = 0; for (const entry of entries) { try { const response = await fetch(entry.path); if (!response.ok) throw new Error('arquivo não disponível'); const parsed = parseDxf(await response.text()); state.strings.push({ id: `project-string-${entry.id}-${Date.now()}-${Math.random()}`, name: entry.path, label: entry.label, ...parsed }); loaded += 1; } catch (error) { notify(`${entry.label}: ${error.message}`, 'error'); } } if (!loaded) throw new Error('Nenhuma poligonal de projeto pôde ser importada.'); renderStringList(); state.contourKey = ''; render(); notify(`${loaded} poligonal(is) do projeto importada(s).`); }
async function loadBundledAreas() { const entries = state.config.areasProjeto || []; if (!entries.length) throw new Error('Nenhuma área de projeto foi configurada.'); let loaded = 0; for (const entry of entries) { try { const response = await fetch(entry.path); if (!response.ok) throw new Error('arquivo não disponível'); const parsed = parseDxf(await response.text()); state.areas.push({ id: `project-area-${entry.id}-${Date.now()}-${Math.random()}`, name: entry.path, label: entry.label, status: 'liberado', ...parsed }); loaded += 1; } catch (error) { notify(`${entry.label}: ${error.message}`, 'error'); } } if (!loaded) throw new Error('Nenhuma área de projeto pôde ser importada.'); renderAreaList(); render(); notify(`${loaded} área(s) do projeto importada(s).`); }
function renderStringList() { const container = $('stringList'); container.innerHTML = ''; if (!state.strings.length) { container.innerHTML = '<div class="empty-state">Nenhuma poligonal carregada.</div>'; return; } state.strings.forEach((item) => { const row = document.createElement('div'); row.className = 'string-item'; const input = document.createElement('input'); input.value = item.label; input.maxLength = state.config.validation.maxLabelLength; input.setAttribute('aria-label', `Nome da string ${item.name}`); input.addEventListener('input', () => { item.label = input.value; render(); }); const meta = document.createElement('small'); meta.textContent = `${item.entities.length} entidades · ${item.sourceType.toUpperCase()}`; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-button'; remove.textContent = '×'; remove.title = `Remover ${item.name}`; remove.addEventListener('click', () => { state.strings = state.strings.filter((candidate) => candidate.id !== item.id); state.contourKey = ''; renderStringList(); render(); }); const copy = document.createElement('div'); copy.className = 'string-item-copy'; copy.append(input, meta); row.append(copy, remove); container.append(row); }); }
function renderAreaList() { const container = $('areaList'); container.innerHTML = ''; if (!state.areas.length) { container.innerHTML = '<div class="empty-state">Nenhuma área carregada.</div>'; return; } state.areas.forEach((area) => { const row = document.createElement('div'); row.className = 'area-item'; const copy = document.createElement('div'); copy.className = 'area-item-copy'; const input = document.createElement('input'); input.value = area.label; input.maxLength = state.config.validation.maxLabelLength; input.setAttribute('aria-label', `Nome da área ${area.name}`); input.addEventListener('input', () => { area.label = input.value; render(); }); const meta = document.createElement('small'); meta.textContent = `${area.entities.length} entidades · classificação automática`; copy.append(input, meta); const badge = document.createElement('span'); badge.dataset.areaStatus = area.id; badge.className = `area-status ${area.status}`; badge.textContent = area.status === 'evacuar' ? 'RAIO · EVACUAR' : 'FORA DO RAIO · LIBERADO'; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-button'; remove.textContent = '×'; remove.title = `Remover ${area.name}`; remove.addEventListener('click', () => { state.areas = state.areas.filter((candidate) => candidate.id !== area.id); renderAreaList(); render(); }); row.append(copy, badge, remove); container.append(row); }); }
function renderPointList() {
  const container = $('pointList'); if (!container) return; container.innerHTML = '';
  const groups = [['firing', 'Ponto de disparo', state.firingPoints], ['blocking', 'Ponto de bloqueio', state.blockingPoints], ['card', 'Entrega de cartões', state.cardPoints]];
  const total = groups.reduce((sum, [, , points]) => sum + points.length, 0);
  if (!total) { container.innerHTML = '<div class="empty-state">Nenhum ponto marcado no croqui.</div>'; return; }
  groups.forEach(([kind, title, points]) => points.forEach((point, index) => {
    const row = document.createElement('div'); row.className = 'point-item';
    const swatch = document.createElement('span'); swatch.className = `point-swatch ${kind}`;
    const copy = document.createElement('div'); copy.className = 'point-item-copy';
    const name = document.createElement('strong'); name.textContent = point.label || `${title} ${index + 1}`;
    const meta = document.createElement('small'); meta.textContent = `${title} · X ${point.x.toFixed(2)} · Y ${point.y.toFixed(2)}`;
    copy.append(name, meta); const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-button'; remove.textContent = '×'; remove.title = `Remover ${title}`;
    remove.addEventListener('click', () => { const target = kind === 'firing' ? state.firingPoints : kind === 'blocking' ? state.blockingPoints : state.cardPoints; target.splice(target.indexOf(point), 1); renderPointList(); render(); });
    row.append(swatch, copy, remove); container.append(row);
  }));
}
function activatePlacement(type) { if (!state.lastRender?.bounds) { notify('Carregue um ortomosaico ou uma geometria antes de marcar pontos.', 'error'); return; } state.placementMode = type; $('reportCanvas').classList.add('placing-point'); const labels = { firing: 'ponto de disparo', blocking: 'ponto de bloqueio', card: 'ponto de entrega dos cartões' }; notify(`Clique no croqui para marcar o ${labels[type]}.`); }
function canvasToGeo(event) {
  const result = state.lastRender; const canvas = $('reportCanvas'); const rect = canvas.getBoundingClientRect(); const pixelX = (event.clientX - rect.left) * canvas.width / rect.width; const pixelY = (event.clientY - rect.top) * canvas.height / rect.height; const map = result.map; if (pixelX < map.x || pixelX > map.x + map.width || pixelY < map.y || pixelY > map.y + map.height) return null;
  const bounds = result.bounds; const worldWidth = Math.max(bounds.maxX - bounds.minX, 1); const worldHeight = Math.max(bounds.maxY - bounds.minY, 1); const scale = Math.min(map.width / worldWidth, map.height / worldHeight); const offsetX = map.x + (map.width - worldWidth * scale) / 2; const offsetY = map.y + (map.height - worldHeight * scale) / 2;
  return { x: bounds.minX + (pixelX - offsetX) / scale, y: bounds.maxY - (pixelY - offsetY) / scale };
}
function handleCanvasClick(event) { if (!state.placementMode) return; const point = canvasToGeo(event); if (!point) { notify('Clique dentro da área do mapa para posicionar o ponto.', 'error'); return; } const type = state.placementMode; const labels = { firing: 'Ponto de disparo', blocking: 'Ponto de bloqueio', card: 'Ponto de entrega' }; const label = window.prompt(`Nome do ${labels[type].toLowerCase()}:`, `${labels[type]} ${(type === 'firing' ? state.firingPoints : type === 'blocking' ? state.blockingPoints : state.cardPoints).length + 1}`); if (label === null) return; const record = { ...point, label: label.trim() || labels[type] };
  if (type === 'firing') state.firingPoints.push(record); else if (type === 'blocking') state.blockingPoints.push(record); else state.cardPoints.push(record);
  state.placementMode = null; $('reportCanvas').classList.remove('placing-point'); renderPointList(); render(); notify(`${labels[type]} marcado no croqui.`);
}
function parseManualBounds() { const values = ['minX', 'minY', 'maxX', 'maxY'].map((id) => Number($(id).value)); if (values.some((value) => !Number.isFinite(value))) return null; const [minX, minY, maxX, maxY] = values; if (maxX <= minX || maxY <= minY) throw new Error('Os limites do mapa precisam formar uma extensão válida.'); return { minX, minY, maxX, maxY }; }
async function loadReference() { const image = await loadImageBlob(await fetch('assets/referencia-base.jpg').then((response) => { if (!response.ok) throw new Error('A imagem de referência não está disponível.'); return response.blob(); })); state.baseImage = { image, bounds: null, name: 'referencia-base.jpg' }; state.orthoLayers = []; state.baseImages = [state.baseImage]; $('backgroundState').textContent = 'Mapa de referência carregado, sem georreferenciamento.'; render(); notify('Mapa de referência carregado.'); }
function clearAll() { state.baseImage = null; state.baseImages = []; state.orthoLayers = []; state.strings = []; state.areas = []; state.firingPoints = []; state.blockingPoints = []; state.cardPoints = []; state.placementMode = null; state.radiusContours = []; state.contourKey = ''; state.boundsMode = 'auto'; state.manualBounds = null; $('reportForm').reset(); populateOrthoCatalog(); $('autoExtent').checked = true; $('manualBounds').hidden = true; $('googleState').textContent = 'Chave opcional'; $('googleState').className = 'status-pill muted'; $('backgroundState').textContent = 'Sem imagem de fundo. A prancha usará o fundo técnico.'; $('reportCanvas').classList.remove('placing-point'); renderStringList(); renderAreaList(); renderPointList(); render(); notify('Formulário limpo.'); }
function wire() {
  $('backgroundFile').addEventListener('change', async (event) => { if (!event.target.files[0]) return; try { await handleBackground(event.target.files[0]); } catch (error) { notify(error.message, 'error'); } });
  $('projectGeoTiffButton').addEventListener('click', async () => { try { await loadProjectGeoTiff(); } catch (error) { notify(error.message, 'error'); } });
  $('loadAllOrthomosaicsButton').addEventListener('click', async () => { try { await loadAllCatalogOrthomosaics(); } catch (error) { notify(error.message, 'error'); } });
  $('loadOrthomosaicButton').addEventListener('click', async () => { try { await loadCatalogOrthomosaic(); } catch (error) { notify(error.message, 'error'); } });
  $('orthomosaicReplacementFile').addEventListener('change', async (event) => { if (!event.target.files[0]) return; try { await replaceCatalogOrthomosaic(event.target.files[0]); } catch (error) { notify(error.message, 'error'); } event.target.value = ''; });
  $('restoreOrthoButton').addEventListener('click', async () => { try { await restoreCatalogOrthomosaic(); } catch (error) { notify(error.message, 'error'); } });
  $('googleSatelliteButton').addEventListener('click', async () => { try { await loadGoogleSatellite(); } catch (error) { $('googleState').textContent = 'Indisponível'; $('googleState').className = 'status-pill error'; notify(error.message, 'error'); } });
  $('stringFile').addEventListener('change', async (event) => { const files = [...event.target.files]; if (!files.length) return; await handleStrings(files); event.target.value = ''; });
  $('loadProjectStringsButton').addEventListener('click', async () => { try { await loadBundledStrings(); } catch (error) { notify(error.message, 'error'); } });
  $('areaFiles').addEventListener('change', async (event) => { for (const file of [...event.target.files]) { try { state.areas.push(await parseAreaFile(file)); } catch (error) { notify(`${file.name}: ${error.message}`, 'error'); } } renderAreaList(); render(); event.target.value = ''; });
  $('loadProjectAreasButton').addEventListener('click', async () => { try { await loadBundledAreas(); } catch (error) { notify(error.message, 'error'); } });
  $('addFiringPointButton').addEventListener('click', () => activatePlacement('firing'));
  $('addBlockingPointButton').addEventListener('click', () => activatePlacement('blocking'));
  $('addCardPointButton').addEventListener('click', () => activatePlacement('card'));
  $('reportCanvas').addEventListener('click', handleCanvasClick);
  ['company', 'date', 'time', 'location', 'observation', 'peopleRadius', 'machineRadius'].forEach((id) => $(id).addEventListener('input', () => { if (id.includes('Radius')) state.contourKey = ''; render(); }));
  $('autoExtent').addEventListener('change', () => { state.boundsMode = $('autoExtent').checked ? 'auto' : 'manual'; $('manualBounds').hidden = $('autoExtent').checked; if (!$('autoExtent').checked) { ensureContours(); const bounds = mergeBounds([boundsOf(stringEntities()), ...state.areas.map((area) => boundsOf(area.entities || [])), boundsOfContours(state.radiusContours), ...(state.baseImages || []).map((image) => image?.bounds), state.baseImage?.bounds]); if (bounds) Object.entries(bounds).forEach(([key, value]) => { $(key).value = value; }); } render(); });
  ['minX', 'minY', 'maxX', 'maxY'].forEach((id) => $(id).addEventListener('input', () => { try { state.manualBounds = parseManualBounds(); render(); } catch { } }));
  $('referenceButton').addEventListener('click', async () => { try { await loadReference(); } catch (error) { notify(error.message, 'error'); } });
  $('clearButton').addEventListener('click', clearAll);
  $('pdfButton').addEventListener('click', () => { try { if (!state.strings.length && !state.areas.length) throw new Error('Adicione ao menos uma string ou área antes de gerar o PDF.'); if (state.boundsMode === 'manual') state.manualBounds = parseManualBounds(); downloadReportPdf($('reportCanvas'), model(), state.config); notify('PDF gerado e baixado.'); } catch (error) { notify(error.message, 'error'); } });
}

async function start() { try { const response = await fetch('./config.json', { cache: 'no-store' }); if (!response.ok) throw new Error('Não foi possível carregar a configuração do projeto.'); state.config = await response.json(); try { state.logoImage = await loadImageBlob(await fetch('assets/mvv-logo.png').then((asset) => asset.blob())); } catch { state.logoImage = null; } try { state.enaexLogo = await loadImageBlob(await fetch('assets/enaex-logo-white.png').then((asset) => asset.blob())); } catch { state.enaexLogo = null; } try { state.blockingIcon = await loadImageBlob(await fetch('assets/cavalete-bloqueio.png').then((asset) => asset.blob())); } catch { state.blockingIcon = null; } try { state.cardIcon = await loadImageBlob(await fetch('assets/cartao-bloqueio.png').then((asset) => asset.blob())); } catch { state.cardIcon = null; } try { state.savedOverrideIds = new Set((await listOrthoOverrides()).map((item) => item.id)); } catch { state.savedOverrideIds = new Set(); } $('appName').textContent = state.config.app.name; $('appEyebrow').textContent = state.config.app.eyebrow; $('appVersion').textContent = `v${state.config.app.version}`; populateOrthoCatalog(); wire(); renderStringList(); renderAreaList(); renderPointList(); render(); await applyDefaultPreset(); } catch (error) { $('statusText').textContent = 'Erro de configuração'; notify(error.message, 'error'); } }
start();
