import { parseDxf, parseGeoJson } from './src/dxf.js';
import { buildRadiusContours, boundsOf, flattenStringEntities, mergeBounds } from './src/geometry.js';
import { decodeGeoTiff } from './src/geotiff.js';
import { drawReport } from './src/render.js';
import { downloadReportPdf } from './src/pdf.js';

const state = { config: null, baseImage: null, logoImage: null, strings: [], areas: [], radiusContours: [], contourKey: '', boundsMode: 'auto', manualBounds: null };
const $ = (id) => document.getElementById(id);

function notify(message, type = '') { const toast = $('toast'); toast.textContent = message; toast.className = `toast show ${type}`; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.className = 'toast'; }, 4200); }
function readNumber(id) { const value = Number($(id).value); return Number.isFinite(value) && value >= 0 ? value : 0; }
function radii() { return { people: readNumber('peopleRadius'), machine: readNumber('machineRadius') }; }
function dateLabel() { const value = $('date').value; return value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : 'data não informada'; }
function stringEntities() { return flattenStringEntities(state.strings); }
function model() { return { meta: { company: $('company').value.trim(), date: $('date').value, time: $('time').value, location: $('location').value.trim(), observation: $('observation').value.trim(), dateLabel: dateLabel() }, baseImage: state.baseImage, logoImage: state.logoImage, strings: state.strings, areas: state.areas, radii: radii(), radiusContours: state.radiusContours, boundsMode: state.boundsMode, manualBounds: state.manualBounds }; }
function allEntities() { return [stringEntities(), ...state.areas.map((area) => area.entities || [])].flat(); }
function ensureContours(currentRadii = radii()) { const key = `${state.strings.map((item) => item.id).join('|')}|${currentRadii.people}|${currentRadii.machine}`; if (key !== state.contourKey) { state.radiusContours = buildRadiusContours(stringEntities(), [currentRadii.people, currentRadii.machine]); state.contourKey = key; } }
function updateStatusBadges() { state.areas.forEach((area) => { const badge = document.querySelector(`[data-area-status="${CSS.escape(area.id)}"]`); if (badge) { badge.textContent = area.status === 'evacuar' ? 'RAIO · EVACUAR' : 'FORA DO RAIO · LIBERADO'; badge.className = `area-status ${area.status}`; } }); }
function updateMetrics(renderResult) { $('geometryCount').textContent = allEntities().length; $('endpointCount').textContent = renderResult.endpointCount; $('scaleWarning').textContent = state.boundsMode === 'auto' ? (state.baseImage?.bounds ? 'GeoTIFF georreferenciada' : 'extensão automática') : 'limites informados'; $('statusText').textContent = state.strings.length || state.areas.length ? 'Dados prontos para conferência' : 'Aguardando dados'; $('previewCaption').textContent = state.strings.length || state.areas.length ? `Prancha atualizada em ${new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}.` : 'A prévia será atualizada conforme os dados forem preenchidos.'; updateStatusBadges(); }
function render() { if (!state.config) return; ensureContours(); updateMetrics(drawReport($('reportCanvas'), model(), state.config)); }

function loadImageBlob(blob) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { URL.revokeObjectURL(image.src); resolve(image); }; image.onerror = () => reject(new Error('Não foi possível ler a imagem selecionada.')); image.src = URL.createObjectURL(blob); }); }
async function handleBackground(file) { const extension = file.name.toLowerCase().split('.').pop(); state.baseImage = ['tif', 'tiff'].includes(extension) ? await decodeGeoTiff(file) : { image: await loadImageBlob(file), bounds: null, name: file.name }; $('backgroundState').textContent = state.baseImage.bounds ? `${file.name} · limites geográficos carregados do GeoTIFF.` : `${file.name} carregado para a prévia.`; render(); }
async function loadProjectGeoTiff() { state.baseImage = await decodeGeoTiff('GEOTIFF/20260730_Mina_Reduzida.tif'); $('backgroundState').textContent = `${state.baseImage.name} · SAD69 / UTM 24S · GeoTIFF georreferenciada.`; render(); notify('GeoTIFF georreferenciada carregada.'); }
async function handleStrings(files) { for (const file of files) { try { if (file.size > state.config.validation.maxDxfBytes) throw new Error('O DXF excede o limite de 50 MB.'); const parsed = parseDxf(await file.text()); state.strings.push({ id: `${file.name}-${file.lastModified}-${Math.random()}`, name: file.name, label: file.name.replace(/\.[^.]+$/, ''), ...parsed }); } catch (error) { notify(`${file.name}: ${error.message}`, 'error'); } } renderStringList(); state.contourKey = ''; render(); }
async function parseAreaFile(file) { if (file.size > state.config.validation.maxDxfBytes) throw new Error(`O arquivo ${file.name} excede o limite de 50 MB.`); const extension = file.name.toLowerCase().split('.').pop(); const parsed = extension === 'dxf' ? parseDxf(await file.text()) : parseGeoJson(await file.text()); return { id: `${file.name}-${file.lastModified}-${Math.random()}`, name: file.name, label: file.name.replace(/\.[^.]+$/, ''), status: 'liberado', ...parsed }; }
function renderStringList() { const container = $('stringList'); container.innerHTML = ''; if (!state.strings.length) { container.innerHTML = '<div class="empty-state">Nenhuma poligonal carregada.</div>'; return; } state.strings.forEach((item) => { const row = document.createElement('div'); row.className = 'string-item'; const input = document.createElement('input'); input.value = item.label; input.maxLength = state.config.validation.maxLabelLength; input.setAttribute('aria-label', `Nome da string ${item.name}`); input.addEventListener('input', () => { item.label = input.value; render(); }); const meta = document.createElement('small'); meta.textContent = `${item.entities.length} entidades · ${item.sourceType.toUpperCase()}`; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-button'; remove.textContent = '×'; remove.title = `Remover ${item.name}`; remove.addEventListener('click', () => { state.strings = state.strings.filter((candidate) => candidate.id !== item.id); state.contourKey = ''; renderStringList(); render(); }); const copy = document.createElement('div'); copy.className = 'string-item-copy'; copy.append(input, meta); row.append(copy, remove); container.append(row); }); }
function renderAreaList() { const container = $('areaList'); container.innerHTML = ''; if (!state.areas.length) { container.innerHTML = '<div class="empty-state">Nenhuma área carregada.</div>'; return; } state.areas.forEach((area) => { const row = document.createElement('div'); row.className = 'area-item'; const copy = document.createElement('div'); copy.className = 'area-item-copy'; const input = document.createElement('input'); input.value = area.label; input.maxLength = state.config.validation.maxLabelLength; input.setAttribute('aria-label', `Nome da área ${area.name}`); input.addEventListener('input', () => { area.label = input.value; render(); }); const meta = document.createElement('small'); meta.textContent = `${area.entities.length} entidades · classificação automática`; copy.append(input, meta); const badge = document.createElement('span'); badge.dataset.areaStatus = area.id; badge.className = `area-status ${area.status}`; badge.textContent = area.status === 'evacuar' ? 'RAIO · EVACUAR' : 'FORA DO RAIO · LIBERADO'; const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'remove-button'; remove.textContent = '×'; remove.title = `Remover ${area.name}`; remove.addEventListener('click', () => { state.areas = state.areas.filter((candidate) => candidate.id !== area.id); renderAreaList(); render(); }); row.append(copy, badge, remove); container.append(row); }); }
function parseManualBounds() { const values = ['minX', 'minY', 'maxX', 'maxY'].map((id) => Number($(id).value)); if (values.some((value) => !Number.isFinite(value))) return null; const [minX, minY, maxX, maxY] = values; if (maxX <= minX || maxY <= minY) throw new Error('Os limites do mapa precisam formar uma extensão válida.'); return { minX, minY, maxX, maxY }; }
async function loadReference() { const image = await loadImageBlob(await fetch('assets/referencia-base.jpg').then((response) => { if (!response.ok) throw new Error('A imagem de referência não está disponível.'); return response.blob(); })); state.baseImage = { image, bounds: null, name: 'referencia-base.jpg' }; $('backgroundState').textContent = 'Mapa de referência carregado, sem georreferenciamento.'; render(); notify('Mapa de referência carregado.'); }
function clearAll() { state.baseImage = null; state.strings = []; state.areas = []; state.radiusContours = []; state.contourKey = ''; state.boundsMode = 'auto'; state.manualBounds = null; $('reportForm').reset(); $('autoExtent').checked = true; $('manualBounds').hidden = true; $('backgroundState').textContent = 'Sem imagem de fundo. A prancha usará o fundo técnico.'; renderStringList(); renderAreaList(); render(); notify('Formulário limpo.'); }
function wire() {
  $('backgroundFile').addEventListener('change', async (event) => { if (!event.target.files[0]) return; try { await handleBackground(event.target.files[0]); } catch (error) { notify(error.message, 'error'); } });
  $('projectGeoTiffButton').addEventListener('click', async () => { try { await loadProjectGeoTiff(); } catch (error) { notify(error.message, 'error'); } });
  $('stringFile').addEventListener('change', async (event) => { const files = [...event.target.files]; if (!files.length) return; await handleStrings(files); event.target.value = ''; });
  $('areaFiles').addEventListener('change', async (event) => { for (const file of [...event.target.files]) { try { state.areas.push(await parseAreaFile(file)); } catch (error) { notify(`${file.name}: ${error.message}`, 'error'); } } renderAreaList(); render(); event.target.value = ''; });
  ['company', 'date', 'time', 'location', 'observation', 'peopleRadius', 'machineRadius'].forEach((id) => $(id).addEventListener('input', () => { if (id.includes('Radius')) state.contourKey = ''; render(); }));
  $('autoExtent').addEventListener('change', () => { state.boundsMode = $('autoExtent').checked ? 'auto' : 'manual'; $('manualBounds').hidden = $('autoExtent').checked; if (!$('autoExtent').checked) { const bounds = mergeBounds([state.baseImage?.bounds, boundsOf(stringEntities()), ...state.areas.map((area) => boundsOf(area.entities || []))]); if (bounds) Object.entries(bounds).forEach(([key, value]) => { $(key).value = value; }); } render(); });
  ['minX', 'minY', 'maxX', 'maxY'].forEach((id) => $(id).addEventListener('input', () => { try { state.manualBounds = parseManualBounds(); render(); } catch { } }));
  $('referenceButton').addEventListener('click', async () => { try { await loadReference(); } catch (error) { notify(error.message, 'error'); } });
  $('clearButton').addEventListener('click', clearAll);
  $('pdfButton').addEventListener('click', () => { try { if (!state.strings.length && !state.areas.length) throw new Error('Adicione ao menos uma string ou área antes de gerar o PDF.'); if (state.boundsMode === 'manual') state.manualBounds = parseManualBounds(); downloadReportPdf($('reportCanvas'), model(), state.config); notify('PDF gerado e baixado.'); } catch (error) { notify(error.message, 'error'); } });
}

async function start() { try { const response = await fetch('./config.json', { cache: 'no-store' }); if (!response.ok) throw new Error('Não foi possível carregar a configuração do projeto.'); state.config = await response.json(); try { state.logoImage = await loadImageBlob(await fetch('assets/mvv-logo.png').then((asset) => asset.blob())); } catch { state.logoImage = null; } $('appName').textContent = state.config.app.name; $('appEyebrow').textContent = state.config.app.eyebrow; $('appVersion').textContent = `v${state.config.app.version}`; wire(); renderStringList(); renderAreaList(); render(); } catch (error) { $('statusText').textContent = 'Erro de configuração'; notify(error.message, 'error'); } }
start();
