import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { parseDxf, parseGeoJson } from '../src/dxf.js';
import { areaIntersectsContours, boundsOf, boundsOfContours, buildRadiusContours, dedupeEntities, differenceEntityWithContours, fitBoundsToAspect, flattenStringEntities, getStringEndpoints, intersectEntityWithContours, paddedBounds, pointIntersectsContours, unionContourPolygons } from '../src/geometry.js';
import { safeFileName } from '../src/pdf.js';

const dxf = await fs.readFile(new URL('../POLIGONAIS/r030826.dxf', import.meta.url), 'latin1');
const parsed = parseDxf(dxf);
vm.runInThisContext(await fs.readFile(new URL('../vendor/polygon-clipping.min.js', import.meta.url), 'utf8'));
assert.equal(parsed.sourceType, 'dxf');
assert.ok(parsed.entities.length >= 3, 'o DXF de referência deve conter as três strings');
assert.ok(parsed.entities.every((entity) => entity.points.length >= 2), 'cada string precisa ter vértices');
assert.ok(getStringEndpoints(parsed.entities).length >= 3, 'as extremidades devem ser identificadas');
const contours = buildRadiusContours(parsed.entities, [700, 300]);
assert.equal(contours.length, 2, 'os dois raios devem gerar dois contornos únicos');
assert.ok(contours.every((contour) => contour.polygons.length === 1), 'cada raio precisa gerar um único cerco unificado');
const savedUnion = globalThis.polygonClipping.union;
globalThis.polygonClipping.union = () => { throw new Error('falha de união simulada'); };
const fallbackContours = buildRadiusContours(parsed.entities, [700]);
assert.equal(fallbackContours[0].polygons.length, 1, 'uma falha de união não pode desenhar cápsulas individuais');
assert.equal(fallbackContours[0].fallback, true, 'a falha de união precisa ser sinalizada como simplificação segura');
globalThis.polygonClipping.union = savedUnion;
globalThis.polygonClipping = { union: (...polygons) => polygons };
assert.equal(unionContourPolygons([[[[0, 0], [10, 0], [10, 10], [0, 0]]], [[[5, 0], [15, 0], [15, 10], [5, 0]]]]).length, 2, 'a normalização precisa aceitar polígonos válidos sem criar raios extras');
const bounds = boundsOf(parsed.entities);
const contourBounds = boundsOfContours(contours);
assert.ok(contourBounds.minX < bounds.minX && contourBounds.maxX > bounds.maxX, 'os raios precisam ampliar a extensão horizontal');
assert.ok(contourBounds.minY < bounds.minY && contourBounds.maxY > bounds.maxY, 'os raios precisam ampliar a extensão vertical');
assert.ok(bounds.maxX > bounds.minX && bounds.maxY > bounds.minY, 'a extensão precisa ser válida');
const expanded = paddedBounds(bounds);
assert.ok(expanded.minX < bounds.minX && expanded.maxY > bounds.maxY, 'a extensão automática precisa ter margem');
const areaDxf = await fs.readFile(new URL('../ÁREA DE INFLUÊNCIA/DXF/EVACUAR.dxf', import.meta.url), 'latin1');
const structurePolygonsDxf = await fs.readFile(new URL('../ESTRUTURAS PROXIMAS/Pligonais das Estruturas Proximas.dxf', import.meta.url), 'latin1');
const structurePolygons = parseDxf(structurePolygonsDxf);
assert.ok(structurePolygons.entities.length >= 54, 'as poligonais novas devem conter as áreas das estruturas');
assert.ok(structurePolygons.entities.every((entity) => entity.closed && entity.points.length >= 3), 'cada poligonal de estrutura precisa ser fechada');
const combinedStructureDxf = await fs.readFile(new URL('../ESTRUTURAS PROXIMAS/ID - PONTOS + Pligonais das Estruturas Proximas.dxf', import.meta.url), 'latin1');
const combinedStructures = parseDxf(combinedStructureDxf);
assert.ok(combinedStructures.entities.length >= 54, 'o DXF combinado precisa conter as poligonais das estruturas');
assert.ok(combinedStructures.entities.every((entity) => entity.closed && entity.points.length >= 3), 'as poligonais combinadas precisam ser fechadas');
assert.equal(dedupeEntities(combinedStructures.entities).length, 48, 'as duplicatas geométricas do DXF combinado devem ser removidas no carregamento');
for (const source of ['ID - PONTOS.dwg', 'ID - PONTOS.dxf']) {
  const sourceStat = await fs.stat(new URL(`../ESTRUTURAS PROXIMAS/${source}`, import.meta.url));
  assert.ok(sourceStat.size > 0, `${source} precisa existir como fonte dos pontos atualizados`);
}
const parsedArea = parseDxf(areaDxf);
assert.ok(parsedArea.entities.length >= 10, 'o DXF de áreas de referência precisa ler os HATCHs');
assert.ok(parsedArea.entities.every((entity) => entity.closed), 'as áreas HATCH precisam ser fechadas');
assert.equal(dedupeEntities(parsedArea.entities).length, 11, 'as áreas de evacuação não devem perder geometrias distintas');
const releasedAreaDxf = await fs.readFile(new URL('../ÁREA DE INFLUÊNCIA/DXF/LIBERADO.dxf', import.meta.url), 'latin1');
const parsedReleasedArea = parseDxf(releasedAreaDxf);
assert.equal(dedupeEntities(parsedReleasedArea.entities).length, 34, 'as duplicatas geométricas das áreas liberadas devem ser removidas no carregamento');
const structureCatalog = JSON.parse(await fs.readFile(new URL('../data/structures.json', import.meta.url), 'utf8'));
const appConfig = JSON.parse(await fs.readFile(new URL('../config.json', import.meta.url), 'utf8'));
const appHtml = await fs.readFile(new URL('../index.html', import.meta.url), 'utf8');
const renderSource = await fs.readFile(new URL('../src/render.js', import.meta.url), 'utf8');
const onlineBackend = await fs.readFile(new URL('../backend/Code.gs', import.meta.url), 'utf8');
assert.equal(appConfig.onlineCatalog.enabled, true, 'o catálogo online precisa estar habilitado');
assert.equal(appConfig.defaultPreset.observation, 'Setor Técnico de Operações - Enaex Brasil.');
assert.deepEqual(appConfig.defaultPreset.pointIconSizes, { firing: 48, blocking: 20, card: 20 });
assert.equal(appConfig.defaultPreset.areaNumberSize, 6);
assert.match(renderSource, /showLabel = true/);
assert.match(renderSource, /function drawStructurePositionLabel/);
assert.match(renderSource, /structure\.positions \|\| \[\]/, 'os rótulos precisam usar as posições reais do catálogo');
assert.match(renderSource, /structure\.points\.forEach\(\(point\) => drawStructurePositionLabel/);
assert.match(renderSource, /colors\.blueHatch/, 'a hachura azul deve usar a cor suavizada configurada');
assert.match(renderSource, /colors\.redHatch/, 'a hachura vermelha deve usar a cor suavizada configurada');
assert.match(renderSource, /drawHatchedEntity\(ctx, entity, transform, colors\.blueHatch, colors\.blueSoft, colors\.blue\)/, 'o contorno azul deve permanecer destacado');
assert.match(renderSource, /drawHatchedPolygon\(ctx, polygon, transform, colors\.redHatch, colors\.redSoft, colors\.red\)/, 'o contorno vermelho deve permanecer destacado');
assert.match(renderSource, /const hatchEntities = model\.areas\.filter\(\(area\) => area\.catalogId !== 'estruturas-proximas'\)/, 'as poligonais das estruturas não devem virar uma camada de hachura');
assert.equal(appConfig.defaultPreset.structurePointsSource.dxf, 'ESTRUTURAS PROXIMAS/ID - PONTOS.dxf');
assert.equal(appConfig.areasProjeto.find((area) => area.id === 'estruturas-proximas')?.path, 'ESTRUTURAS PROXIMAS/Pligonais das Estruturas Proximas.dxf');
assert.equal(appConfig.ortomosaicos.length, 4, 'o catálogo deve conter o GeoTIFF principal e os três ortomosaicos atuais');
for (const ortho of appConfig.ortomosaicos) assert.ok((await fs.stat(new URL(`../${ortho.path}`, import.meta.url))).size > 0, `o ortomosaico ${ortho.path} precisa existir`);
assert.match(appHtml, /id="exportProjectButton"/);
assert.match(appHtml, /id="importProjectFile"/);
assert.match(appConfig.onlineCatalog.endpoint, /^https:\/\/script\.google\.com\/macros\/s\//, 'o endpoint online precisa ser um Web App do Apps Script');
assert.match(onlineBackend, /function doGet\(event\)/, 'o backend precisa expor leitura online');
assert.match(onlineBackend, /function doPost\(event\)/, 'o backend precisa expor publicação online');
assert.match(onlineBackend, /LockService\.getScriptLock\(\)/, 'a publicação online precisa serializar gravações');
assert.equal(structureCatalog.structures.length, 54, 'o catálogo deve conter as 54 estruturas nomeadas da planilha');
assert.equal(new Set(structureCatalog.structures.map((structure) => structure.id)).size, 54, 'os identificadores das estruturas devem ser únicos');
assert.equal(structureCatalog.structures.reduce((total, structure) => total + structure.positions.length, 0), 59, 'o catálogo deve preservar todas as 59 posições fornecidas');
assert.equal(structureCatalog.pointsSource.extractedPositions, 59, 'a origem dos pontos precisa registrar as 59 posições');
assert.equal(structureCatalog.structures.find((structure) => structure.id === '41')?.name, 'PORTARIA');
assert.equal(structureCatalog.structures.find((structure) => structure.id === '42')?.name, 'PILHA DE TOPSOIL');
assert.equal(structureCatalog.structures.find((structure) => structure.id === '40')?.name, 'ACESSO PRINCIPAL');
assert.ok(structureCatalog.structures.find((structure) => structure.id === '08')?.positions.length > 1, 'IDs compostos devem preservar posições repetidas');
assert.ok(structureCatalog.pageMap.width > 0 && structureCatalog.pageMap.height > 0, 'o catálogo deve guardar a extensão cartográfica da página fonte');

const geo = parseGeoJson(JSON.stringify({ type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'EVACUAR' }, geometry: { type: 'Polygon', coordinates: [[[0, 0], [10, 0], [10, 10], [0, 0]]] } }] }));
assert.equal(geo.entities.length, 1);
assert.equal(geo.entities[0].closed, true);
assert.equal(flattenStringEntities([{ entities: parsed.entities }, { entities: parsed.entities.slice(0, 1) }]).length, parsed.entities.length + 1);
const closedContour = buildRadiusContours([{ type: 'polyline', closed: true, points: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }] }], [1]);
assert.equal(areaIntersectsContours([{ type: 'point', points: [{ x: 5, y: 5 }] }], closedContour), true, 'a poligonal fechada precisa receber buffer também no último segmento');
const contour = [{ polygons: [[[[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]]]], radius: 5 }];
assert.equal(areaIntersectsContours([{ type: 'polyline', closed: true, points: [{ x: 4, y: 4 }, { x: 6, y: 4 }, { x: 6, y: 6 }, { x: 4, y: 4 }] }], contour), true);
assert.equal(areaIntersectsContours([{ type: 'polyline', closed: true, points: [{ x: 20, y: 20 }, { x: 22, y: 20 }, { x: 22, y: 22 }, { x: 20, y: 20 }] }], contour), false);
assert.equal(pointIntersectsContours({ x: 5, y: 5 }, contour), true, 'um ponto dentro do contorno deve ser evacuado');
assert.equal(pointIntersectsContours({ x: 15, y: 15 }, contour), false, 'um ponto fora do contorno deve ser liberado');
assert.equal(pointIntersectsContours({ x: 0, y: 5 }, contour), true, 'um ponto sobre o limite do contorno deve ser evacuado');
const aspectBounds = fitBoundsToAspect({ minX: 0, minY: 0, maxX: 10, maxY: 10 }, 2);
assert.equal(aspectBounds.maxX - aspectBounds.minX, 20, 'a extensão deve cobrir a proporção horizontal do mapa');
globalThis.polygonClipping = { intersection: () => [[[[0, 0], [1, 0], [1, 1], [0, 0]]]] };
assert.equal(intersectEntityWithContours({ closed: true, points: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }, { x: 0, y: 0 }] }, contour).length, 1, 'um sólido fechado precisa retornar a interseção para a hachura vermelha');
globalThis.polygonClipping = { difference: (subject) => subject };
assert.equal(differenceEntityWithContours({ closed: true, points: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }, { x: 0, y: 0 }] }, contour).length, 1, 'a base azul precisa aceitar a diferença geométrica dos raios');
assert.equal(safeFileName('Aviso de Detonação 04/08/2026'), 'aviso-de-detonacao-04-08-2026');
console.log(`PASS: DXF ${parsed.entities.length} entidades, ${getStringEndpoints(parsed.entities).length} extremidades, GeoJSON e nome de arquivo validados.`);
