import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { parseDxf, parseGeoJson } from '../src/dxf.js';
import { areaIntersectsContours, boundsOf, boundsOfContours, buildRadiusContours, fitBoundsToAspect, flattenStringEntities, getStringEndpoints, intersectEntityWithContours, paddedBounds, pointIntersectsContours } from '../src/geometry.js';
import { safeFileName } from '../src/pdf.js';

const dxf = await fs.readFile(new URL('../POLIGONAIS/r030826.dxf', import.meta.url), 'latin1');
const parsed = parseDxf(dxf);
vm.runInThisContext(await fs.readFile(new URL('../vendor/polygon-clipping.min.js', import.meta.url), 'utf8'));
assert.equal(parsed.sourceType, 'dxf');
assert.ok(parsed.entities.length >= 3, 'o DXF de referência deve conter as três strings');
assert.ok(parsed.entities.every((entity) => entity.points.length >= 2), 'cada string precisa ter vértices');
assert.ok(getStringEndpoints(parsed.entities).length >= 3, 'as extremidades devem ser identificadas');
const contours = buildRadiusContours(parsed.entities, [700, 300]);
assert.equal(contours.length, 2, 'os dois raios devem gerar dois contornos únicos');
assert.ok(contours.every((contour) => contour.polygons.length >= 1), 'cada raio precisa ter uma união geométrica');
const bounds = boundsOf(parsed.entities);
const contourBounds = boundsOfContours(contours);
assert.ok(contourBounds.minX < bounds.minX && contourBounds.maxX > bounds.maxX, 'os raios precisam ampliar a extensão horizontal');
assert.ok(contourBounds.minY < bounds.minY && contourBounds.maxY > bounds.maxY, 'os raios precisam ampliar a extensão vertical');
assert.ok(bounds.maxX > bounds.minX && bounds.maxY > bounds.minY, 'a extensão precisa ser válida');
const expanded = paddedBounds(bounds);
assert.ok(expanded.minX < bounds.minX && expanded.maxY > bounds.maxY, 'a extensão automática precisa ter margem');
const areaDxf = await fs.readFile(new URL('../ÁREA DE INFLUÊNCIA/DXF/EVACUAR.dxf', import.meta.url), 'latin1');
const parsedArea = parseDxf(areaDxf);
assert.ok(parsedArea.entities.length >= 10, 'o DXF de áreas de referência precisa ler os HATCHs');
assert.ok(parsedArea.entities.every((entity) => entity.closed), 'as áreas HATCH precisam ser fechadas');
const structureCatalog = JSON.parse(await fs.readFile(new URL('../data/structures.json', import.meta.url), 'utf8'));
assert.equal(structureCatalog.structures.length, 54, 'o catálogo do PDF deve conter as 54 estruturas numeradas');
assert.equal(new Set(structureCatalog.structures.map((structure) => structure.id)).size, 54, 'os identificadores das estruturas devem ser únicos');
assert.equal(structureCatalog.structures.filter((structure) => structure.statusFromPdf === 'evacuar').length, 29, 'o PDF deve conter 29 estruturas de evacuação');
assert.equal(structureCatalog.structures.filter((structure) => structure.statusFromPdf === 'liberado').length, 25, 'o PDF deve conter 25 estruturas liberadas');
assert.ok(structureCatalog.pageMap.width > 0 && structureCatalog.pageMap.height > 0, 'o catálogo deve guardar a extensão cartográfica da página fonte');

const geo = parseGeoJson(JSON.stringify({ type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'EVACUAR' }, geometry: { type: 'Polygon', coordinates: [[[0, 0], [10, 0], [10, 10], [0, 0]]] } }] }));
assert.equal(geo.entities.length, 1);
assert.equal(geo.entities[0].closed, true);
assert.equal(flattenStringEntities([{ entities: parsed.entities }, { entities: parsed.entities.slice(0, 1) }]).length, parsed.entities.length + 1);
const closedContour = buildRadiusContours([{ type: 'polyline', closed: true, points: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }] }], [1]);
assert.equal(areaIntersectsContours([{ type: 'point', points: [{ x: 5, y: 5 }] }], closedContour), true, 'a poligonal fechada precisa receber buffer também no último segmento');
const contour = [{ polygons: [[[[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]]]], radius: 5 }];
assert.equal(areaIntersectsContours([{ type: 'polyline', closed: true, points: [{ x: 4, y: 4 }, { x: 6, y: 4 }, { x: 6, y: 6 }, { x: 4, y: 4 }] }], contour), true);
assert.equal(areaIntersectsContours([{ type: 'polyline', closed: true, points: [{ x: 20, y: 20 }, { x: 22, y: 20 }, { x: 22, y: 22 }, { x: 20, y: 20 }] }], contour), false);
assert.equal(pointIntersectsContours({ x: 5, y: 5 }, contour), true, 'um ponto dentro do contorno deve ser evacuado');
assert.equal(pointIntersectsContours({ x: 15, y: 15 }, contour), false, 'um ponto fora do contorno deve ser liberado');
assert.equal(pointIntersectsContours({ x: 0, y: 5 }, contour), true, 'um ponto sobre o limite do contorno deve ser evacuado');
const aspectBounds = fitBoundsToAspect({ minX: 0, minY: 0, maxX: 10, maxY: 10 }, 2);
assert.equal(aspectBounds.maxX - aspectBounds.minX, 20, 'a extensão deve cobrir a proporção horizontal do mapa');
globalThis.polygonClipping = { intersection: () => [[[[0, 0], [1, 0], [1, 1], [0, 0]]]] };
assert.equal(intersectEntityWithContours({ closed: true, points: [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }, { x: 0, y: 0 }] }, contour).length, 1, 'um sólido fechado precisa retornar a interseção para a hachura vermelha');
assert.equal(safeFileName('Aviso de Detonação 04/08/2026'), 'aviso-de-detonacao-04-08-2026');
console.log(`PASS: DXF ${parsed.entities.length} entidades, ${getStringEndpoints(parsed.entities).length} extremidades, GeoJSON e nome de arquivo validados.`);
